events { worker_connections 1024; }

http {
    upstream kibana_backend {
        server bluelock-kibana:5601;
    }

    server {
        listen 80;
        server_name siem.blue.local;
        return 301 https://$host$request_uri; # Redirection Zero-Trust
    }

    server {
        listen 443 ssl;
        server_name siem.blue.local;

        ssl_certificate /etc/nginx/certs/siem.crt;
        ssl_certificate_key /etc/nginx/certs/siem.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://kibana_backend;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}