events { worker_connections 1024; }

http {
    # Redirection automatique du HTTP (80) vers le HTTPS (443)
    server {
        listen 80;
        server_name bastion.blue.local;
        return 301 https://$host$request_uri;
    }

    # Configuration HTTPS Sécurisée
    server {
        listen 443 ssl;
        server_name bastion.blue.local;

        # Chemins vers les certificats générés automatiquement par ton script Python
        ssl_certificate /etc/nginx/certs/bastion.crt;
        ssl_certificate_key /etc/nginx/certs/bastion.key;

        # Paramètres TLS durcis (Exigence 27)
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://guacamole:8080/guacamole/;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
        }
    }
}